insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (1, 'Currants', 110.08, 'Ultrasonography of Liver', 27);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (2, 'Chicken - Diced, Cooked', 185.61, 'Removal of Drainage Device from R Tarsal Jt, Extern Approach', 32);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (3, 'Yoplait Drink', 118.6, 'Extraction of Left Sphenoid Sinus, Perc Endo Approach', 30);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (4, 'Lettuce - Boston Bib - Organic', 27.14, 'Transfuse Autol Bone Marrow in Central Art, Perc', 38);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (5, 'Sauce - Marinara', 37.9, 'Augmentative/Alternative Communication System Assessment', 39);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (6, 'Salmon Steak - Cohoe 6 Oz', 179.95, 'Occlusion of Ileum with Intraluminal Device, Via Opening', 13);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (7, 'Celery', 48.59, 'Revision of Autol Sub in R Knee Jt, Open Approach', 12);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (8, 'Pork - Back, Short Cut, Boneless', 84.83, 'Dilate R Temporal Art w 4 Drug-elut, Perc Endo', 11);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (9, 'Carrots - Jumbo', 136.74, 'Inspection of Cervicothoracic Vertebral Disc, Perc Approach', 13);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (10, 'Beer - Upper Canada Light', 190.4, 'Removal of Nonaut Sub from Low Intest Tract, Via Opening', 27);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (11, 'Bread - Roll, Calabrese', 115.84, 'Excision of R Ext Auditory Canal, Perc Endo Approach', 32);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (12, 'Cleaner - Lime Away', 112.81, 'Bypass L Atrium to R Pulm Vn w Zooplastic, Perc Endo', 28);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (13, 'Sole - Dover, Whole, Fresh', 46.75, 'Release Right Ankle Bursa and Ligament, Perc Approach', 42);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (14, 'Coffee Decaf Colombian', 122.11, 'Revision of Autol Sub in Great Vessel, Perc Endo Approach', 25);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (15, 'Juice - Orangina', 142.29, 'Supplement Peroneal Nerve with Autol Sub, Open Approach', 19);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (16, 'Table Cloth 62x114 Colour', 88.39, 'Drainage of Chest Subcu/Fascia with Drain Dev, Open Approach', 24);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (17, 'Bread - Onion Focaccia', 147.47, 'Supplement Perineum Subcu/Fascia w Autol Sub, Open', 41);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (18, 'Wine - Trimbach Pinot Blanc', 44.54, 'Restrict of R Foot Art with Extralum Dev, Perc Endo Approach', 12);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (19, 'White Baguette', 90.94, 'Excision of Right Pelvic Bone, Perc Endo Approach, Diagn', 47);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (20, 'Parsley - Dried', 197.66, 'Extirpation of Matter from L Abd Tendon, Perc Endo Approach', 33);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (21, 'Filter - Coffee', 56.87, 'Inspection of R Metatarsophal Jt, Perc Endo Approach', 50);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (22, 'Veal - Provimi Inside', 62.21, 'Insertion of Infusion Device into Upper Jaw, Open Approach', 35);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (23, 'Pepper - Yellow Bell', 174.56, 'Dilate of Face Art, Bifurc, with 4 Drug-elut, Perc Approach', 38);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (24, 'Lamb - Loin, Trimmed, Boneless', 23.32, 'Repair Right Finger Phalangeal Joint, External Approach', 37);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (25, 'Pears - Fiorelle', 166.2, 'Repair Right Tibia, Open Approach', 30);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (26, 'Tomatoes - Vine Ripe, Yellow', 143.83, 'Drainage of Prostate with Drainage Device, Open Approach', 13);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (27, 'Ice Cream Bar - Rolo Cone', 194.6, 'Revision of Synth Sub in R Up Femur, Perc Approach', 12);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (28, 'Yoghurt Tubes', 43.35, 'Control Bleeding in R Up Extrem, Perc Endo Approach', 27);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (29, 'Chevere Logs', 33.72, 'Insertion of Monitoring Device into Left Lung, Perc Approach', 32);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (30, 'Bread Cranberry Foccacia', 58.34, 'Drainage of Right Patella, Open Approach, Diagnostic', 50);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (31, 'Sage - Rubbed', 120.27, 'Remove Radioact Elem from Up Extrem Subcu/Fascia, Extern', 22);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (32, 'Sardines', 57.24, 'Revision of Nonaut Sub in R Metacarpal, Extern Approach', 23);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (33, 'Muffin Hinge - 211n', 39.54, 'Replacement of Right Fibula with Nonaut Sub, Open Approach', 29);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (34, 'Nut - Walnut, Pieces', 61.26, 'Fusion of Left Hip Joint with Autol Sub, Open Approach', 42);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (35, 'Lamb - Pieces, Diced', 76.43, 'Dilate of Mid Colic Art with 4+ Intralum Dev, Open Approach', 24);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (36, 'Shrimp - Baby, Warm Water', 188.28, 'Remove Infusion Dev from Epididymis/Sperm Cord, Extern', 20);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (37, 'Sauce - Apple, Unsweetened', 96.47, 'Supplement Left Shoulder Joint with Synth Sub, Perc Approach', 37);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (38, 'Rosemary - Primerba, Paste', 188.68, 'Excision of Right Innominate Vein, Perc Endo Approach, Diagn', 13);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (39, 'Ham - Virginia', 114.57, 'Release Right Vitreous, Percutaneous Approach', 39);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (40, 'Potatoes - Peeled', 118.8, 'Restriction of Ileocecal Valve, Perc Endo Approach', 18);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (41, 'Lemonade - Strawberry, 591 Ml', 111.3, 'Excision of Hypothalamus, Percutaneous Approach', 47);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (42, 'Turnip - White, Organic', 159.5, 'Removal of Autol Sub from Vas Deferens, Endo', 44);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (43, 'Cake - Sheet Strawberry', 23.17, 'Supplement L Metacarpal with Autol Sub, Perc Endo Approach', 23);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (44, 'Pesto - Primerba, Paste', 75.07, 'Extirpation of Matter from Optic Nerve, Open Approach', 19);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (45, 'V8 Splash Strawberry Banana', 38.04, 'Revision of Nonaut Sub in Low Tendon, Perc Approach', 27);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (46, 'Wine - Red, Wolf Blass, Yellow', 67.18, 'Removal of Autol Sub from L Rib, Open Approach', 11);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (47, 'Nectarines', 176.96, 'Supplement Left Elbow Joint with Nonaut Sub, Open Approach', 35);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (48, 'Broom And Brush Rack Black', 61.0, 'Excision of Left Vertebral Vein, Perc Approach, Diagn', 49);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (49, 'Shark - Loin', 158.82, 'Removal of Infusion Device from Low Art, Extern Approach', 18);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (50, 'Wine - Red, Cabernet Sauvignon', 161.14, 'Insertion of Ext Fix into L Elbow Jt, Open Approach', 30);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (51, 'Bandage - Flexible Neon', 193.85, 'Excision of Spleen, Percutaneous Approach, Diagnostic', 36);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (52, 'Carrots - Mini Red Organic', 145.35, 'Supplement Left Colic Artery with Synth Sub, Open Approach', 19);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (53, 'Wine - Gato Negro Cabernet', 178.87, 'Fluoroscopy of Pharynx and Epiglottis using Other Contrast', 43);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (54, 'Beets - Pickled', 194.03, 'Supplement L Com Iliac Art with Nonaut Sub, Open Approach', 33);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (55, 'Rum - Mount Gay Eclipes', 158.74, 'Dilation of Middle Esophagus with Intraluminal Device, Endo', 11);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (56, 'Cheese - Brie,danish', 115.08, 'Removal of Drainage Device from L Tarsal Jt, Open Approach', 45);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (57, 'Pork - Loin, Center Cut', 118.5, 'Introduce of Nutritional into Cran Cav/Brain, Open Approach', 36);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (58, 'Veal - Bones', 52.11, 'Extirpate matter from R Int Iliac Art, Bifurc, Open', 18);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (59, 'Wine - Alsace Gewurztraminer', 189.46, 'Detachment at Left Hand, Partial 2nd Ray, Open Approach', 26);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (60, 'Yeast - Fresh, Fleischman', 198.28, 'Bypass L Ureter to R Ureter w Nonaut Sub, Perc Endo', 30);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (61, 'Coke - Diet, 355 Ml', 187.83, 'Division of Right Thumb Phalanx, Percutaneous Approach', 24);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (62, 'Shichimi Togarashi Peppeers', 93.68, 'Repair Sciatic Nerve, Open Approach', 17);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (63, 'Pineapple - Golden', 126.58, 'Extirpation of Matter from R Com Carotid, Perc Endo Approach', 50);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (64, 'Beef - Short Ribs', 51.63, 'Revision of Nonaut Sub in L Toe Phalanx, Extern Approach', 26);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (65, 'Green Scrubbie Pad H.duty', 62.36, 'Revision of Drain Dev in R Up Extrem, Perc Endo Approach', 41);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (66, 'Sauce - White, Mix', 32.95, 'Division of Anal Sphincter, Percutaneous Approach', 22);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (67, 'Quail - Jumbo Boneless', 186.37, 'Excision of Left Toe Phalangeal Joint, Percutaneous Approach', 47);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (68, 'Ecolab - Solid Fusion', 100.97, 'Drainage of R Pleural Cav with Drain Dev, Open Approach', 14);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (69, 'Yogurt - Blueberry, 175 Gr', 41.21, 'Insert of Radioact Elem into R Buttock, Perc Endo Approach', 45);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (70, 'Bread Crumbs - Panko', 84.46, 'Introduce Oth Antineoplastic in Pleural Cav, Perc', 38);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (71, 'Wine - Placido Pinot Grigo', 61.25, 'Drainage of Left Vertebral Artery, Percutaneous Approach', 20);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (72, 'Coffee Decaf Colombian', 185.54, 'Drainage of Right Ovary, External Approach', 20);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (73, 'Spice - Pepper Portions', 136.75, 'Insertion of Infusion Device into Head, Open Approach', 10);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (74, 'Vector Energy Bar', 127.69, 'Plain Radiography of B Tracheobronc Tree using Oth Contrast', 50);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (75, 'Chicken - Whole Fryers', 114.29, 'Monitoring of Cardiac Rhythm, Percutaneous Approach', 45);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (76, 'Cattail Hearts', 149.37, 'Occlusion of Left Upper Lobe Bronchus, Endo', 35);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (77, 'Trout - Hot Smkd, Dbl Fillet', 65.61, 'Revision of Int Fix in Lum Vertebra, Perc Endo Approach', 30);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (78, 'Veal - Chops, Split, Frenched', 110.07, 'HDR Brachytherapy of Thyroid using Californium 252', 11);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (79, 'Calypso - Lemonade', 46.32, 'Drainage of Larynx, Endo', 23);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (80, 'Sugar - Fine', 187.94, 'Supplement Penis with Autol Sub, Perc Endo Approach', 48);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (81, 'Mikes Hard Lemonade', 113.64, 'Reposition Right External Iliac Vein, Percutaneous Approach', 20);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (82, 'Soup - Knorr, French Onion', 67.74, 'Extirpation of Matter from L Hand Vein, Perc Endo Approach', 19);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (83, 'Cheese - Blue', 125.56, 'Transfer Right Hip Muscle with Skin, Subcu, Open Approach', 13);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (84, 'Cornflakes', 148.75, 'Occlusion Head Lymph w Intralum Dev, Perc Endo', 48);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (85, 'Chevere Logs', 89.21, 'Extirpation of Matter from Left Femoral Vein, Perc Approach', 32);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (86, 'Rice Wine - Aji Mirin', 35.04, 'Alteration of L Up Eyelid with Autol Sub, Open Approach', 39);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (87, 'Flower - Commercial Spider', 198.64, 'Drainage of Right Fibula, Open Approach, Diagnostic', 49);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (88, 'Plate Foam Laminated 9in Blk', 195.32, 'Insertion of Int Fix into Thor Jt, Open Approach', 38);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (89, 'Bread Sour Rolls', 96.45, 'MRI of Port/Splanch Vein using Oth Contrast, Unenh, Enhance', 48);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (90, 'Nut - Pine Nuts, Whole', 38.2, 'Insertion of Pedcl Stabl Dev into Lumsac Jt, Perc Approach', 45);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (91, 'Pepper - Cubanelle', 124.56, 'Extirpation of Matter from Pericardium, Perc Approach', 31);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (92, 'Pepper - Gypsy Pepper', 110.1, 'Excision of R Ext Auditory Canal, Via Opening, Diagn', 28);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (93, 'Beer - Guiness', 105.88, 'Supplement L Axilla Art with Autol Sub, Perc Approach', 44);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (94, 'Coke - Diet, 355 Ml', 159.65, 'Drainage of Left Axillary Artery, Perc Endo Approach', 40);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (95, 'Sole - Fillet', 52.31, 'Repair Left Shoulder Joint, Percutaneous Approach', 10);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (96, 'Wiberg Super Cure', 61.45, 'Insertion of Stimulator Lead into Up Muscle, Perc Approach', 16);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (97, 'Wine - Balbach Riverside', 176.14, 'Supplement Transverse Colon with Nonaut Sub, Via Opening', 36);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (98, 'Bacardi Limon', 192.13, 'Revise Infusion Pump in Up Extrem Subcu/Fascia, Open', 44);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (99, 'Eggplant - Baby', 75.79, 'Bypass Left Vertebral Vein to Upper Vein, Open Approach', 23);
insert into PLATILLO (ID_PLATILLO, NOMBRE, PRECIO, DESCRIPCIÓN, STOCK) values (100, 'Bag Clear 10 Lb', 41.6, 'Introduction of Insulin into Central Artery, Perc Approach', 35);
